# -*- coding: utf-8 -*-
# pylint: disable=W0212,C0301,C0121
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x10order_book.proto\x12.aea.eightballer.order_book_subscription.v0_1_0\"\xee\x07\n\x10OrderBookMessage\x12\x64\n\x05\x65rror\x18\x05 \x01(\x0b\x32S.aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Error_PerformativeH\x00\x12|\n\x11order_book_update\x18\x06 \x01(\x0b\x32_.aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Order_Book_Update_PerformativeH\x00\x12l\n\tsubscribe\x18\x07 \x01(\x0b\x32W.aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Subscribe_PerformativeH\x00\x12p\n\x0bunsubscribe\x18\x08 \x01(\x0b\x32Y.aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Unsubscribe_PerformativeH\x00\x1a\x80\x01\n\tOrderBook\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04\x62ids\x18\x03 \x03(\x05\x12\x0c\n\x04\x61sks\x18\x04 \x03(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x05\x12\x10\n\x08\x64\x61tetime\x18\x06 \x01(\t\x12\r\n\x05nonce\x18\x07 \x01(\x05\x1a\x95\x01\n\x16Subscribe_Performative\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tprecision\x18\x03 \x01(\t\x12\x18\n\x10precision_is_set\x18\x04 \x01(\x08\x12\x10\n\x08interval\x18\x05 \x01(\x05\x12\x17\n\x0finterval_is_set\x18\x06 \x01(\x08\x1a?\n\x18Unsubscribe_Performative\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x1a\x80\x01\n\x1eOrder_Book_Update_Performative\x12^\n\norder_book\x18\x01 \x01(\x0b\x32J.aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.OrderBook\x1a'\n\x12\x45rror_Performative\x12\x11\n\terror_msg\x18\x01 \x01(\tB\x0e\n\x0cperformativeb\x06proto3"
)


_ORDERBOOKMESSAGE = DESCRIPTOR.message_types_by_name["OrderBookMessage"]
_ORDERBOOKMESSAGE_ORDERBOOK = _ORDERBOOKMESSAGE.nested_types_by_name["OrderBook"]
_ORDERBOOKMESSAGE_SUBSCRIBE_PERFORMATIVE = _ORDERBOOKMESSAGE.nested_types_by_name["Subscribe_Performative"]
_ORDERBOOKMESSAGE_UNSUBSCRIBE_PERFORMATIVE = _ORDERBOOKMESSAGE.nested_types_by_name["Unsubscribe_Performative"]
_ORDERBOOKMESSAGE_ORDER_BOOK_UPDATE_PERFORMATIVE = _ORDERBOOKMESSAGE.nested_types_by_name[
    "Order_Book_Update_Performative"
]
_ORDERBOOKMESSAGE_ERROR_PERFORMATIVE = _ORDERBOOKMESSAGE.nested_types_by_name["Error_Performative"]
OrderBookMessage = _reflection.GeneratedProtocolMessageType(
    "OrderBookMessage",
    (_message.Message,),
    {
        "OrderBook": _reflection.GeneratedProtocolMessageType(
            "OrderBook",
            (_message.Message,),
            {
                "DESCRIPTOR": _ORDERBOOKMESSAGE_ORDERBOOK,
                "__module__": "order_book_pb2"
                # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.OrderBook)
            },
        ),
        "Subscribe_Performative": _reflection.GeneratedProtocolMessageType(
            "Subscribe_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _ORDERBOOKMESSAGE_SUBSCRIBE_PERFORMATIVE,
                "__module__": "order_book_pb2"
                # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Subscribe_Performative)
            },
        ),
        "Unsubscribe_Performative": _reflection.GeneratedProtocolMessageType(
            "Unsubscribe_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _ORDERBOOKMESSAGE_UNSUBSCRIBE_PERFORMATIVE,
                "__module__": "order_book_pb2"
                # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Unsubscribe_Performative)
            },
        ),
        "Order_Book_Update_Performative": _reflection.GeneratedProtocolMessageType(
            "Order_Book_Update_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _ORDERBOOKMESSAGE_ORDER_BOOK_UPDATE_PERFORMATIVE,
                "__module__": "order_book_pb2"
                # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Order_Book_Update_Performative)
            },
        ),
        "Error_Performative": _reflection.GeneratedProtocolMessageType(
            "Error_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _ORDERBOOKMESSAGE_ERROR_PERFORMATIVE,
                "__module__": "order_book_pb2"
                # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage.Error_Performative)
            },
        ),
        "DESCRIPTOR": _ORDERBOOKMESSAGE,
        "__module__": "order_book_pb2"
        # @@protoc_insertion_point(class_scope:aea.eightballer.order_book_subscription.v0_1_0.OrderBookMessage)
    },
)
_sym_db.RegisterMessage(OrderBookMessage)
_sym_db.RegisterMessage(OrderBookMessage.OrderBook)
_sym_db.RegisterMessage(OrderBookMessage.Subscribe_Performative)
_sym_db.RegisterMessage(OrderBookMessage.Unsubscribe_Performative)
_sym_db.RegisterMessage(OrderBookMessage.Order_Book_Update_Performative)
_sym_db.RegisterMessage(OrderBookMessage.Error_Performative)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ORDERBOOKMESSAGE._serialized_start = 69
    _ORDERBOOKMESSAGE._serialized_end = 1075
    _ORDERBOOKMESSAGE_ORDERBOOK._serialized_start = 542
    _ORDERBOOKMESSAGE_ORDERBOOK._serialized_end = 670
    _ORDERBOOKMESSAGE_SUBSCRIBE_PERFORMATIVE._serialized_start = 673
    _ORDERBOOKMESSAGE_SUBSCRIBE_PERFORMATIVE._serialized_end = 822
    _ORDERBOOKMESSAGE_UNSUBSCRIBE_PERFORMATIVE._serialized_start = 824
    _ORDERBOOKMESSAGE_UNSUBSCRIBE_PERFORMATIVE._serialized_end = 887
    _ORDERBOOKMESSAGE_ORDER_BOOK_UPDATE_PERFORMATIVE._serialized_start = 890
    _ORDERBOOKMESSAGE_ORDER_BOOK_UPDATE_PERFORMATIVE._serialized_end = 1018
    _ORDERBOOKMESSAGE_ERROR_PERFORMATIVE._serialized_start = 1020
    _ORDERBOOKMESSAGE_ERROR_PERFORMATIVE._serialized_end = 1059
# @@protoc_insertion_point(module_scope)
