# Auto-generated by tool

"""Test messages module for the spot_asset protocol."""

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.mail.base import Envelope

from packages.eightballer.protocols.spot_asset.message import SpotAssetMessage
from packages.eightballer.protocols.spot_asset.tests.performatives import (
    End,
    Error,
    SpotAsset,
    GetSpotAsset,
    GetSpotAssets,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def perform_message_test(performative, model) -> None:
    """Test message encode/decode."""

    msg = SpotAssetMessage(
        performative=performative,
        **shallow_dump(model),
    )

    msg.to = "receiver"
    assert msg._is_consistent()  # noqa: SLF001
    envelope = Envelope(to=msg.to, sender="sender", message=msg)
    envelope_bytes = envelope.encode()

    actual_envelope = Envelope.decode(envelope_bytes)
    expected_envelope = envelope

    assert expected_envelope.to == actual_envelope.to
    assert expected_envelope.sender == actual_envelope.sender
    assert expected_envelope.protocol_specification_id == actual_envelope.protocol_specification_id
    assert expected_envelope.message != actual_envelope.message

    actual_msg = SpotAssetMessage.serializer.decode(actual_envelope.message_bytes)
    actual_msg.to = actual_envelope.to
    actual_msg.sender = actual_envelope.sender
    expected_msg = msg
    assert expected_msg == actual_msg


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetSpotAsset))
def test_get_spot_asset_messages(model):
    """Test for the 'GET_SPOT_ASSET' protocol message encode and decode."""

    perform_message_test(SpotAssetMessage.Performative.GET_SPOT_ASSET, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(SpotAsset))
def test_spot_asset_messages(model):
    """Test for the 'SPOT_ASSET' protocol message encode and decode."""

    perform_message_test(SpotAssetMessage.Performative.SPOT_ASSET, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetSpotAssets))
def test_get_spot_assets_messages(model):
    """Test for the 'GET_SPOT_ASSETS' protocol message encode and decode."""

    perform_message_test(SpotAssetMessage.Performative.GET_SPOT_ASSETS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Error))
def test_error_messages(model):
    """Test for the 'ERROR' protocol message encode and decode."""

    perform_message_test(SpotAssetMessage.Performative.ERROR, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(End))
def test_end_messages(model):
    """Test for the 'END' protocol message encode and decode."""

    perform_message_test(SpotAssetMessage.Performative.END, model)
