name: derived_cow
author: eightballer
version: 0.1.0
description: A new service, scaffolded by the Adev cli from eightballer/derive_arbitrage_agent:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint:
  __init__.py: bafybeifdc5tk6topwmcviejgkm3lmrhnhk6fqqvh76hv7xwg3qkhxifznm
  tests/__init__.py: bafybeiausykbndof27hjfgwqg6nnmk7zw7lyytwzekih3gszwdypbtxjka
  tests/test_service.py: bafybeicplirjoql5q3l5zjl5xrgamnoxuj3year7u2vrtfnzzllzeyutuy
fingerprint_ignore_patterns: []
agent: eightballer/derive_arbitrage_agent:0.1.0:bafybeiamirsicd37lh57wjn33jjb74is565v4zkfeh5hebftdug2wh2eeq
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/simple_fsm:0.1.0
type: skill
models:
  arbitrage_strategy:
    args:
      dexs:
        derive:
        - derive
        cowswap: ${COW_CHAINS:list:["arbitrum"]}
        balancer: []
      strategy_public_id: eightballer/lbtc_arbitrage:0.1.0
