# Auto-generated by tool

"""Test dialogues module for the balances protocol."""

from unittest.mock import MagicMock

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.configurations.data_types import PublicId

from packages.eightballer.protocols.balances.message import BalancesMessage
from packages.eightballer.protocols.balances.dialogues import (
    BalancesDialogues,
)
from packages.eightballer.protocols.balances.tests.performatives import (
    GetBalance,
    GetAllBalances,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def validate_dialogue(performative, model):
    """Validate successful dialogue instantiation."""

    skill_context = MagicMock()
    skill_context.skill_id = PublicId(
        name="mock_name",
        author="mock_author",
    )

    dialogues = BalancesDialogues(
        name="test_balances_dialogues",
        skill_context=skill_context,
    )

    dialogue = dialogues.create(
        counterparty="dummy_counterparty",
        performative=performative,
        **shallow_dump(model),
    )

    assert dialogue is not None


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetAllBalances))
def test_get_all_balances_dialogues(model):
    """Test for the 'GET_ALL_BALANCES' protocol."""
    validate_dialogue(BalancesMessage.Performative.GET_ALL_BALANCES, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetBalance))
def test_get_balance_dialogues(model):
    """Test for the 'GET_BALANCE' protocol."""
    validate_dialogue(BalancesMessage.Performative.GET_BALANCE, model)
