# Auto-generated by tool

"""Test messages module for the orders protocol."""

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.mail.base import Envelope

from packages.eightballer.protocols.orders.message import OrdersMessage
from packages.eightballer.protocols.orders.tests.performatives import (
    Error,
    Order,
    Orders,
    GetOrder,
    GetOrders,
    CancelOrder,
    CreateOrder,
    OrderCreated,
    GetSettlements,
    OrderCancelled,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def perform_message_test(performative, model) -> None:
    """Test message encode/decode."""

    msg = OrdersMessage(
        performative=performative,
        **shallow_dump(model),
    )

    msg.to = "receiver"
    assert msg._is_consistent()  # noqa: SLF001
    envelope = Envelope(to=msg.to, sender="sender", message=msg)
    envelope_bytes = envelope.encode()

    actual_envelope = Envelope.decode(envelope_bytes)
    expected_envelope = envelope

    assert expected_envelope.to == actual_envelope.to
    assert expected_envelope.sender == actual_envelope.sender
    assert expected_envelope.protocol_specification_id == actual_envelope.protocol_specification_id
    assert expected_envelope.message != actual_envelope.message

    actual_msg = OrdersMessage.serializer.decode(actual_envelope.message_bytes)
    actual_msg.to = actual_envelope.to
    actual_msg.sender = actual_envelope.sender
    expected_msg = msg
    assert expected_msg == actual_msg


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(CreateOrder))
def test_create_order_messages(model):
    """Test for the 'CREATE_ORDER' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.CREATE_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(OrderCreated))
def test_order_created_messages(model):
    """Test for the 'ORDER_CREATED' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.ORDER_CREATED, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(CancelOrder))
def test_cancel_order_messages(model):
    """Test for the 'CANCEL_ORDER' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.CANCEL_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(OrderCancelled))
def test_order_cancelled_messages(model):
    """Test for the 'ORDER_CANCELLED' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.ORDER_CANCELLED, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetOrders))
def test_get_orders_messages(model):
    """Test for the 'GET_ORDERS' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.GET_ORDERS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetSettlements))
def test_get_settlements_messages(model):
    """Test for the 'GET_SETTLEMENTS' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.GET_SETTLEMENTS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetOrder))
def test_get_order_messages(model):
    """Test for the 'GET_ORDER' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.GET_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Order))
def test_order_messages(model):
    """Test for the 'ORDER' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Orders))
def test_orders_messages(model):
    """Test for the 'ORDERS' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.ORDERS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Error))
def test_error_messages(model):
    """Test for the 'ERROR' protocol message encode and decode."""

    perform_message_test(OrdersMessage.Performative.ERROR, model)
