# Auto-generated by tool

"""Test dialogues module for the orders protocol."""

from unittest.mock import MagicMock

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.configurations.data_types import PublicId

from packages.eightballer.protocols.orders.message import OrdersMessage
from packages.eightballer.protocols.orders.dialogues import (
    OrdersDialogues,
)
from packages.eightballer.protocols.orders.tests.performatives import (
    GetOrder,
    GetOrders,
    CancelOrder,
    CreateOrder,
    GetSettlements,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def validate_dialogue(performative, model):
    """Validate successful dialogue instantiation."""

    skill_context = MagicMock()
    skill_context.skill_id = PublicId(
        name="mock_name",
        author="mock_author",
    )

    dialogues = OrdersDialogues(
        name="test_orders_dialogues",
        skill_context=skill_context,
    )

    dialogue = dialogues.create(
        counterparty="dummy_counterparty",
        performative=performative,
        **shallow_dump(model),
    )

    assert dialogue is not None


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(CreateOrder))
def test_create_order_dialogues(model):
    """Test for the 'CREATE_ORDER' protocol."""
    validate_dialogue(OrdersMessage.Performative.CREATE_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(CancelOrder))
def test_cancel_order_dialogues(model):
    """Test for the 'CANCEL_ORDER' protocol."""
    validate_dialogue(OrdersMessage.Performative.CANCEL_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetOrder))
def test_get_order_dialogues(model):
    """Test for the 'GET_ORDER' protocol."""
    validate_dialogue(OrdersMessage.Performative.GET_ORDER, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetOrders))
def test_get_orders_dialogues(model):
    """Test for the 'GET_ORDERS' protocol."""
    validate_dialogue(OrdersMessage.Performative.GET_ORDERS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetSettlements))
def test_get_settlements_dialogues(model):
    """Test for the 'GET_SETTLEMENTS' protocol."""
    validate_dialogue(OrdersMessage.Performative.GET_SETTLEMENTS, model)
