# Auto-generated by tool

"""Test dialogues module for the positions protocol."""

from unittest.mock import MagicMock

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.configurations.data_types import PublicId

from packages.eightballer.protocols.positions.message import PositionsMessage
from packages.eightballer.protocols.positions.dialogues import (
    PositionsDialogues,
)
from packages.eightballer.protocols.positions.tests.performatives import (
    GetPosition,
    GetAllPositions,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def validate_dialogue(performative, model):
    """Validate successful dialogue instantiation."""

    skill_context = MagicMock()
    skill_context.skill_id = PublicId(
        name="mock_name",
        author="mock_author",
    )

    dialogues = PositionsDialogues(
        name="test_positions_dialogues",
        skill_context=skill_context,
    )

    dialogue = dialogues.create(
        counterparty="dummy_counterparty",
        performative=performative,
        **shallow_dump(model),
    )

    assert dialogue is not None


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetAllPositions))
def test_get_all_positions_dialogues(model):
    """Test for the 'GET_ALL_POSITIONS' protocol."""
    validate_dialogue(PositionsMessage.Performative.GET_ALL_POSITIONS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetPosition))
def test_get_position_dialogues(model):
    """Test for the 'GET_POSITION' protocol."""
    validate_dialogue(PositionsMessage.Performative.GET_POSITION, model)
