# Auto-generated by tool

"""Test messages module for the markets protocol."""

from pydantic import BaseModel
from hypothesis import HealthCheck, given, settings, strategies as st
from aea.mail.base import Envelope

from packages.eightballer.protocols.markets.message import MarketsMessage
from packages.eightballer.protocols.markets.tests.performatives import (
    Error,
    Market,
    GetMarket,
    AllMarkets,
    GetAllMarkets,
)


def shallow_dump(model: BaseModel) -> dict:
    """Shallow dump pydantic model."""

    return {name: getattr(model, name) for name in model.__class__.model_fields}


def perform_message_test(performative, model) -> None:
    """Test message encode/decode."""

    msg = MarketsMessage(
        performative=performative,
        **shallow_dump(model),
    )

    msg.to = "receiver"
    assert msg._is_consistent()  # noqa: SLF001
    envelope = Envelope(to=msg.to, sender="sender", message=msg)
    envelope_bytes = envelope.encode()

    actual_envelope = Envelope.decode(envelope_bytes)
    expected_envelope = envelope

    assert expected_envelope.to == actual_envelope.to
    assert expected_envelope.sender == actual_envelope.sender
    assert expected_envelope.protocol_specification_id == actual_envelope.protocol_specification_id
    assert expected_envelope.message != actual_envelope.message

    actual_msg = MarketsMessage.serializer.decode(actual_envelope.message_bytes)
    actual_msg.to = actual_envelope.to
    actual_msg.sender = actual_envelope.sender
    expected_msg = msg
    assert expected_msg == actual_msg


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetAllMarkets))
def test_get_all_markets_messages(model):
    """Test for the 'GET_ALL_MARKETS' protocol message encode and decode."""

    perform_message_test(MarketsMessage.Performative.GET_ALL_MARKETS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(GetMarket))
def test_get_market_messages(model):
    """Test for the 'GET_MARKET' protocol message encode and decode."""

    perform_message_test(MarketsMessage.Performative.GET_MARKET, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(AllMarkets))
def test_all_markets_messages(model):
    """Test for the 'ALL_MARKETS' protocol message encode and decode."""

    perform_message_test(MarketsMessage.Performative.ALL_MARKETS, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Market))
def test_market_messages(model):
    """Test for the 'MARKET' protocol message encode and decode."""

    perform_message_test(MarketsMessage.Performative.MARKET, model)


@settings(deadline=1000, suppress_health_check=[HealthCheck.too_slow])
@given(st.from_type(Error))
def test_error_messages(model):
    """Test for the 'ERROR' protocol message encode and decode."""

    perform_message_test(MarketsMessage.Performative.ERROR, model)
