# Auto-generated by tool

"""This module contains the classes required for asset_bridging dialogue management.

- AssetBridgingDialogue: The dialogue class maintains state of a dialogue and manages it.
- AssetBridgingDialogues: The dialogues class keeps track of all dialogues.
"""

from abc import ABC
from typing import cast
from collections.abc import Callable

from aea.common import Address
from aea.skills.base import Model
from aea.protocols.base import Message
from aea.protocols.dialogue.base import Dialogue, Dialogues, DialogueLabel

from packages.zarathustra.protocols.asset_bridging.message import AssetBridgingMessage


def _role_from_first_message(message: Message, sender: Address) -> Dialogue.Role:  # noqa: ARG001
    """Infer the role of the agent from an incoming/outgoing first message."""
    return AssetBridgingDialogue.Role.AGENT


class AssetBridgingDialogue(Dialogue):
    """The asset_bridging dialogue class maintains state of a dialogue and manages it."""

    INITIAL_PERFORMATIVES: frozenset[Message.Performative] = frozenset(
        {
            AssetBridgingMessage.Performative.REQUEST_BRIDGE,
            AssetBridgingMessage.Performative.REQUEST_STATUS,
        }
    )
    TERMINAL_PERFORMATIVES: frozenset[Message.Performative] = frozenset(
        {
            AssetBridgingMessage.Performative.BRIDGE_STATUS,
            AssetBridgingMessage.Performative.ERROR,
        }
    )
    VALID_REPLIES: dict[Message.Performative, frozenset[Message.Performative]] = {
        AssetBridgingMessage.Performative.REQUEST_BRIDGE: frozenset(
            {
                AssetBridgingMessage.Performative.BRIDGE_STATUS,
                AssetBridgingMessage.Performative.ERROR,
            }
        ),
        AssetBridgingMessage.Performative.REQUEST_STATUS: frozenset(
            {
                AssetBridgingMessage.Performative.BRIDGE_STATUS,
                AssetBridgingMessage.Performative.ERROR,
            }
        ),
        AssetBridgingMessage.Performative.BRIDGE_STATUS: frozenset(),
        AssetBridgingMessage.Performative.ERROR: frozenset(),
    }

    class Role(Dialogue.Role):
        """This class defines the agent's role in a asset_bridging dialogue."""

        AGENT = "agent"
        LEDGER = "ledger"

    class EndState(Dialogue.EndState):
        """This class defines the end states of a asset_bridging dialogue."""

        SUCCESSFUL = 0
        FAILED = 1

    def __init__(
        self,
        dialogue_label: DialogueLabel,
        self_address: Address,
        role: Dialogue.Role,
        message_class: type[AssetBridgingMessage] = AssetBridgingMessage,
    ) -> None:
        """Initialize a dialogue.

        Args:
        ----
            dialogue_label: the identifier of the dialogue
            self_address: the address of the entity for whom this dialogue is maintained
            role: the role of the agent this dialogue is maintained for
            message_class: the message class used

        """
        Dialogue.__init__(
            self,
            dialogue_label=dialogue_label,
            message_class=message_class,
            self_address=self_address,
            role=role,
        )


class BaseAssetBridgingDialogues(Dialogues, ABC):
    """This class keeps track of all asset_bridging dialogues."""

    END_STATES = frozenset(
        {
            AssetBridgingDialogue.EndState.SUCCESSFUL,
            AssetBridgingDialogue.EndState.FAILED,
        }
    )
    _keep_terminal_state_dialogues = False

    def __init__(
        self,
        self_address: Address,
        role_from_first_message: Callable[[Message, Address], Dialogue.Role] = _role_from_first_message,
        dialogue_class: type[AssetBridgingDialogue] = AssetBridgingDialogue,
    ) -> None:
        """Initialize dialogues.

        Args:
        ----
            self_address: the address of the entity for whom dialogues are maintained
            dialogue_class: the dialogue class used
            role_from_first_message: the callable determining role from first message

        """
        Dialogues.__init__(
            self,
            self_address=self_address,
            end_states=cast(frozenset[Dialogue.EndState], self.END_STATES),
            message_class=AssetBridgingMessage,
            dialogue_class=dialogue_class,
            role_from_first_message=role_from_first_message,
        )


class AssetBridgingDialogues(BaseAssetBridgingDialogues, Model):
    """This class defines the dialogues used in asset_bridging."""

    def __init__(self, **kwargs):
        """Initialize dialogues."""
        Model.__init__(self, keep_terminal_state_dialogues=False, **kwargs)
        BaseAssetBridgingDialogues.__init__(
            self,
            self_address=str(self.context.skill_id),
            role_from_first_message=_role_from_first_message,
        )
